//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactPM
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string FullName { get; set; }
        public string Tell { get; set; }
        public string Email { get; set; }
        public string Text { get; set; }
        public string RegDateFa { get; set; }
        public string TraceCode { get; set; }
        public string Reply { get; set; }
        public bool IsRead { get; set; }
        public string ReplyDateFa { get; set; }
        public string IP { get; set; }
    }
}
