//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageContent
    {
        public int ID { get; set; }
        public string Url { get; set; }
        public string Title { get; set; }
        public string Text { get; set; }
        public int ViewCount { get; set; }
        public bool OnlyUsersCanSee { get; set; }
        public string RobotAccess { get; set; }
        public string SeoTitle { get; set; }
        public string Description { get; set; }
        public string KeyWords { get; set; }
        public bool Editable { get; set; }
    }
}
