//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostGroupMapping
    {
        public int ID { get; set; }
        public int PostGroupID { get; set; }
        public int PostID { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual PostGroup PostGroup { get; set; }
    }
}
