//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Post()
        {
            this.PostComments = new HashSet<PostComment>();
            this.PostGroupMappings = new HashSet<PostGroupMapping>();
        }
    
        public int ID { get; set; }
        public string Url { get; set; }
        public string Title { get; set; }
        public string SeoTitle { get; set; }
        public string Text { get; set; }
        public string KeyWords { get; set; }
        public string SeoDescription { get; set; }
        public string Pic { get; set; }
        public string Cover { get; set; }
        public string RegDate { get; set; }
        public string RobotAccess { get; set; }
        public bool OnlyUserCanComment { get; set; }
        public bool IsCommentActive { get; set; }
        public int ViewCount { get; set; }
        public string Brief { get; set; }
        public bool IsActive { get; set; }
        public bool IsPublished { get; set; }
        public string PublishDate { get; set; }
        public int LikeCount { get; set; }
        public Nullable<short> Type { get; set; }
        public Nullable<int> LanguageID { get; set; }
        public bool IsDeleted { get; set; }
        public string DeleteDesc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostComment> PostComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostGroupMapping> PostGroupMappings { get; set; }
    }
}
