//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostComment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PostComment()
        {
            this.PostComment1 = new HashSet<PostComment>();
        }
    
        public int ID { get; set; }
        public int PostID { get; set; }
        public int ParentID { get; set; }
        public int UserID { get; set; }
        public string Text { get; set; }
        public string AuthorEmail { get; set; }
        public string AuthorName { get; set; }
        public string AuthorUrl { get; set; }
        public string AuthorIP { get; set; }
        public string RegDate { get; set; }
        public string RegTime { get; set; }
        public bool IsRead { get; set; }
        public bool IsApproved { get; set; }
    
        public virtual Post Post { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostComment> PostComment1 { get; set; }
        public virtual PostComment PostComment2 { get; set; }
    }
}
