//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Product_Group_Mapping = new HashSet<Product_Group_Mapping>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string SeoTitle { get; set; }
        public string SeoDescription { get; set; }
        public int CategoryID { get; set; }
        public string Url { get; set; }
        public string Pic { get; set; }
        public bool IsDeleted { get; set; }
        public string FullDescription { get; set; }
        public int ViewCount { get; set; }
        public int Priority { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Group_Mapping> Product_Group_Mapping { get; set; }
    }
}
