//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersData
    {
        public string Id { get; set; }
        public string FullName { get; set; }
        public string Avatar { get; set; }
        public string Mobile { get; set; }
        public bool MobileConFirmed { get; set; }
        public Nullable<System.DateTime> LastMobConfRequest { get; set; }
        public string LastLoginDate { get; set; }
        public bool IsBanned { get; set; }
        public string BannedMsg { get; set; }
        public string About { get; set; }
        public string MoarefID { get; set; }
        public int Money { get; set; }
        public short AccountType { get; set; }
        public Nullable<System.DateTime> AccountExpireDateEn { get; set; }
        public bool AutoUpgrade { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string UserName { get; set; }
        public System.DateTime RegDateEn { get; set; }
    }
}
